version: '3.9'
services:
  db:
    image: iproffx_clone
    container_name: sasdb
    restart: always
    environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=AlaisA
    ports:
        - '3308:3306'
    expose:
        - '3308'
        
  restapi:
    image: 89e64285f575
    container_name: sas_rest    
    build: 
      context: .
    ports:
        - '8000:80'      