# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  PROJECT_ID: sas22iproff
  SERVICE: sas22iproff-restapi          #google run service name
  REGION: us-central1
  

on:
  push:   
    branches:
      - 'features/**'
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal --filter 'Category=UnitTest'
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Setup Cloud cli
       uses: google-github-actions/setup-gcloud@v0
       with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_email: sas22iproff@sas22iproff.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}       
    
     - name: Authorize Docker push
       run: gcloud auth configure-docker
      
     - name: Build and Push Container
      
       run: |-
        cd SAS22
        pwd
        ls
        docker build . -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
        
     - name: Deploy to Cloud Run      
       run: gcloud run deploy ${{ env.PROJECT_ID }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} --region ${{ env.REGION }} --platform managed

  apitests:
    needs: deploy
    runs-on: ubuntu-latest
    
     steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal --filter 'Category=ApiTest'